### ISSUE TITLE
Name of the repo should be tox-packaging

### ISSUE THREAD

**Issue by GrayHatter** [zetok/arch-repo-tox#1]
That way we can offer build scripts for other distros than just Arch Linux

**Comment by urras** [comment]
What other distros did you have in mind, @GrayHatter?

**Comment by GrayHatter** [comment]
# .deb

https://wiki.debian.org/HowToPackageForDebian && http://packaging.ubuntu.com/html/packaging-new-software.html

# .rpm

https://fedoraproject.org/wiki/How_to_create_an_RPM_package && https://wiki.centos.org/HowTos/SetupRpmBuildEnvironment && https://wiki.mageia.org/en/Packagers_RPM_tutorial && https://en.opensuse.org/openSUSE:Build_Service_Tutorial

# slack

http://www.slackwiki.com/Building_A_Package

**Comment by zetok** [comment]
Um, this repo is for arch only, since I agree with

```
<sqt> I want each distros maintainer to only have access to what they maintain
```

There can be created separate repos for other distros though

Edit: if no one will do it before me, I'll look into making repos for packaging for those distros after this repo will get into proper shape (no unverified PKGBUILDs)
