### ISSUE TITLE
package "tox" need to provide "toxcore"? or\and need to reneme to "toxcore"?

### ISSUE THREAD

**Issue by polymorphm** [zetok/arch-repo-tox#14]
good day!

package "tox" need to provide "toxcore"? or\and need to reneme to "toxcore"?

see official packages in Archlinux:

https://www.archlinux.org/packages/community/x86_64/toxcore/ -- provides "tox" -- [ok!]

https://www.archlinux.org/packages/community/x86_64/tuntox/ -- depend from "toxcore" -- [what?!]

thanks in advance!

**Comment by polymorphm** [comment]
see -- https://bugs.archlinux.org/task/46936

**Comment by quininer** [comment]
I think rename `toxcore` is more reasonable. see https://github.com/Tox/arch-repo-tox/pull/13#issuecomment-150264386

In fact, the [repo](https://github.com/irungentoo/toxcore) is called `toxcore` instead `tox`.
