### ISSUE TITLE
is openal-soft-tox needed?

### ISSUE THREAD

**Issue by zetok** [zetok/arch-repo-tox#2]
I.e. what exactly is the benefit, and why it justifies maintaining it?

please consider that it can break openal install, and that changes from Tox fork will be upstreamed (provided that they'll withstand test of time in Tox)

**Comment by GrayHatter** [comment]
I remember needing it for µTox but it might be superfluous... want to create a separate branch and reset master?

**Comment by zetok** [comment]
hmm, it was never needed for µTox on Gentoo → IIRC it was only needed for echo cancellation, but now fork of `filter_audio` takes care of it, and if those changes weren't yet merged in master of `filter_audio`, they are going to be there ~soon

I'll just remove it, if there is no real reason to keep it

**Comment by zetok** [comment]
```
[13:43:22] <zetok> irungentoo: is custom-patched openal still needed for removing echo?
[13:44:15] <zetok> I mean, patched filter_audio seemed to quite nicely deal with echo without patched openal, so…
[13:45:24] <irungentoo> yes
```

apparently it's still needed, so the question is whether keeping it (considering that it "may" break normal openal) is something that should be done?

**Comment by zetok** [comment]
Apparently it causes only problems: https://www.reddit.com/r/projecttox/comments/31mk7k/arch_linux_conflicting_packages_openal_and/
