### ISSUE TITLE
qtox-git needs testing

### ISSUE THREAD

**Issue by zetok** [zetok/arch-repo-tox#5]
- check whether builds on top of tox-git and libfilteraudio-git and can be launched
- if possible, it would be nice to check whether it pulls in all needed qt5 dependencies on a system that doesn't have qt

**Comment by haavard** [comment]
Dependencies should be correct, I build in chroots and there are no build errors. Launches and works when tox/libfilteraudio dependencies are fixed.

**Comment by zetok** [comment]
until it will build against master toxcore, it should stay in `unverified`

**Comment by urras** [comment]
@zetok Time to close this?

**Comment by haavard** [comment]
:+1:
